version: '3.7'

services:
  web:
    # build image from the directory that contains the dockerfile
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    # command: bash -c "daphne -b 0.0.0.0 -p 8000 my_app.asgi:application && python manage.py runworker"
    env_file: ./env-dev
    # forward port 8000 from localhost to 8000 of the docker container
    ports:
      - 8000:8000
    links:
      - redis:redis

    volumes:
      # map the backend folder to the docker workdir for easy development
      - ./backend:/usr/src/app
    depends_on:
      - db



  db:
    image: postgres:12.0-alpine
    volumes:
      # named volume
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env-dev


  redis:
    image: redis:alpine
    ports:
      - 6379:6379

# persist the named volume which happens to be the postgres db
volumes:
  postgres_data:


