version: '3.7'

services:
  web:
    # build image from the directory that contains the dockerfile
    build: ./backend
    command: gunicorn my_app.wsgi:application --bind 0.0.0.0:8000
    env_file: ./env-prod
    # forward port 8000 from localhost to 8000 of the docker container
    ports:
      - 8000:8000
    links:
      - redis:redis
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      # named volume
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./env-prod

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

# persist the named volume which happens to be the postgres db
volumes:
  postgres_data:

