version: '3'

services:
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn my_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file: .env
    container_name: scrumbo
    links:
      - redis:redis

    volumes:
      - .:/code
    depends_on:
      - db

db:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data: