# Generated by Django 2.2.6 on 2019-11-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url_friendly_name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('color', models.CharField(default='FFFFFF', max_length=6)),
                ('board', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumbo.Board')),
            ],
        ),
    ]
