# Generated by Django 2.2.6 on 2019-11-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('board', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumbo.Board')),
            ],
        ),
    ]
