# Generated by Django 2.2.6 on 2019-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='column_container_width',
            field=models.IntegerField(default=0),
        ),
    ]
