# Generated by Django 2.2.6 on 2019-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0002_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
