# Generated by Django 2.2.6 on 2019-12-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0002_board_column_container_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='column_container_width',
            field=models.IntegerField(default=700),
        ),
    ]
