# Generated by Django 2.1.7 on 2019-04-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0004_board_url_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='board_id',
        ),
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='scrumbo.Board'),
        ),
    ]
