# Generated by Django 2.1.7 on 2019-04-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0006_auto_20190427_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumbo.Board'),
        ),
    ]
