# Generated by Django 2.1.7 on 2019-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0007_auto_20190427_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='url_friendly_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
