# Generated by Django 2.1.7 on 2019-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0010_auto_20190502_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='x_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='y_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
