# Generated by Django 2.1.7 on 2019-09-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0011_auto_20190831_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='x_position',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='y_position',
            new_name='top',
        ),
    ]
