# Generated by Django 2.1.7 on 2019-10-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0012_auto_20190901_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hex_color',
            field=models.CharField(default='FFFFFF', max_length=6),
        ),
    ]
