# Generated by Django 2.1.7 on 2019-10-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumbo', '0013_note_hex_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='hex_color',
            new_name='color',
        ),
    ]
